from app import app, db, SecretWord

with app.app_context():
    # Check if words already exist
    existing = SecretWord.query.count()
    if existing > 0:
        print(f"Database already has {existing} words. Skipping seed.")
        exit()
    
    words = [
        ('computers','keyboard'),('computers','monitor'),('computers','mouse'),('computers','processor'),('computers','memory'),('computers','software'),('computers','hardware'),('computers','laptop'),('computers','tablet'),('computers','server'),('computers','router'),('computers','printer'),('computers','scanner'),('computers','motherboard'),('computers','graphics'),('computers','storage'),('computers','network'),('computers','firewall'),('computers','database'),('computers','algorithm'),('computers','coding'),('computers','debugging'),('computers','compiler'),('computers','interface'),('computers','programming'),
        ('animals','elephant'),('animals','giraffe'),('animals','lion'),('animals','tiger'),('animals','bear'),('animals','zebra'),('animals','monkey'),('animals','gorilla'),('animals','cheetah'),('animals','leopard'),('animals','kangaroo'),('animals','koala'),('animals','panda'),('animals','hippopotamus'),('animals','rhinoceros'),('animals','crocodile'),('animals','alligator'),('animals','dolphin'),('animals','whale'),('animals','shark'),('animals','octopus'),('animals','jellyfish'),('animals','penguin'),('animals','seal'),('animals','walrus'),
        ('birds','eagle'),('birds','hawk'),('birds','falcon'),('birds','owl'),('birds','parrot'),('birds','peacock'),('birds','flamingo'),('birds','pelican'),('birds','hummingbird'),('birds','woodpecker'),('birds','cardinal'),('birds','bluebird'),('birds','robin'),('birds','sparrow'),('birds','crow'),('birds','raven'),('birds','seagull'),('birds','albatross'),('birds','ostrich'),('birds','emu'),('birds','turkey'),('birds','chicken'),('birds','duck'),('birds','goose'),('birds','swan'),
        ('automotive','engine'),('automotive','transmission'),('automotive','brakes'),('automotive','steering'),('automotive','suspension'),('automotive','exhaust'),('automotive','radiator'),('automotive','battery'),('automotive','alternator'),('automotive','carburetor'),('automotive','headlight'),('automotive','bumper'),('automotive','windshield'),('automotive','dashboard'),('automotive','gearbox'),('automotive','clutch'),('automotive','turbocharger'),('automotive','camshaft'),('automotive','piston'),('automotive','crankshaft'),('automotive','sparkplug'),('automotive','muffler'),('automotive','catalytic'),('automotive','differential'),('automotive','axle'),
        ('trains','locomotive'),('trains','caboose'),('trains','passenger'),('trains','freight'),('trains','railroad'),('trains','platform'),('trains','station'),('trains','conductor'),('trains','engineer'),('trains','ticket'),('trains','schedule'),('trains','track'),('trains','junction'),('trains','crossing'),('trains','signal'),('trains','tunnel'),('trains','bridge'),('trains','steam'),('trains','diesel'),('trains','electric'),('trains','subway'),('trains','monorail'),('trains','maglev'),('trains','trolley'),('trains','tram'),
        ('food','pizza'),('food','hamburger'),('food','sandwich'),('food','burrito'),('food','taco'),('food','spaghetti'),('food','lasagna'),('food','sushi'),('food','noodles'),('food','rice'),('food','salad'),('food','soup'),('food','steak'),('food','chicken'),('food','fish'),('food','cheese'),('food','bread'),('food','pancakes'),('food','waffles'),('food','cereal'),('food','yogurt'),('food','chocolate'),('food','cookie'),('food','cake'),('food','donut'),
        ('health','vitamin'),('health','exercise'),('health','nutrition'),('health','diet'),('health','fitness'),('health','wellness'),('health','medicine'),('health','vaccine'),('health','therapy'),('health','diagnosis'),('health','treatment'),('health','surgery'),('health','recovery'),('health','immune'),('health','antibody'),('health','hygiene'),('health','sanitize'),('health','quarantine'),('health','epidemic'),('health','pandemic'),('health','disease'),('health','infection'),('health','symptom'),('health','prescription'),('health','medication'),
        ('sports','basketball'),('sports','football'),('sports','soccer'),('sports','baseball'),('sports','tennis'),('sports','volleyball'),('sports','swimming'),('sports','hockey'),('sports','cricket'),('sports','rugby'),('sports','golf'),('sports','boxing'),('sports','wrestling'),('sports','gymnastics'),('sports','archery'),('sports','fencing'),('sports','karate'),('sports','judo'),('sports','taekwondo'),('sports','cycling'),('sports','marathon'),('sports','sprinting'),('sports','javelin'),('sports','discus'),('sports','pole'),
        ('hospitals','emergency'),('hospitals','surgery'),('hospitals','intensive'),('hospitals','ward'),('hospitals','clinic'),('hospitals','laboratory'),('hospitals','radiology'),('hospitals','pharmacy'),('hospitals','ambulance'),('hospitals','stretcher'),('hospitals','stethoscope'),('hospitals','syringe'),('hospitals','bandage'),('hospitals','wheelchair'),('hospitals','crutches'),('hospitals','thermometer'),('hospitals','blood'),('hospitals','xray'),('hospitals','ultrasound'),('hospitals','scanner'),('hospitals','defibrillator'),('hospitals','ventilator'),('hospitals','oxygen'),('hospitals','intravenous'),('hospitals','monitor'),
        ('biology','cell'),('biology','nucleus'),('biology','mitochondria'),('biology','chromosome'),('biology','gene'),('biology','protein'),('biology','enzyme'),('biology','membrane'),('biology','tissue'),('biology','organ'),('biology','organism'),('biology','photosynthesis'),('biology','respiration'),('biology','metabolism'),('biology','evolution'),('biology','mutation'),('biology','adaptation'),('biology','ecosystem'),('biology','habitat'),('biology','species'),('biology','bacteria'),('biology','virus'),('biology','antibody'),('biology','vaccine'),('biology','reproduction'),
        ('planets','mercury'),('planets','venus'),('planets','earth'),('planets','mars'),('planets','jupiter'),('planets','saturn'),('planets','uranus'),('planets','neptune'),('planets','moon'),('planets','asteroid'),('planets','comet'),('planets','meteor'),('planets','orbit'),('planets','gravity'),('planets','atmosphere'),('planets','galaxy'),('planets','solar'),('planets','milky'),('planets','nebula'),('planets','constellation'),('planets','telescope'),('planets','satellite'),('planets','spacecraft'),('planets','rocket'),('planets','astronaut'),
        ('geography','mountain'),('geography','valley'),('geography','river'),('geography','ocean'),('geography','lake'),('geography','island'),('geography','peninsula'),('geography','continent'),('geography','desert'),('geography','forest'),('geography','jungle'),('geography','glacier'),('geography','volcano'),('geography','canyon'),('geography','plateau'),('geography','plain'),('geography','coast'),('geography','beach'),('geography','cliff'),('geography','waterfall'),('geography','delta'),('geography','equator'),('geography','latitude'),('geography','longitude'),('geography','hemisphere'),
        ('Islam','mosque'),('Islam','prayer'),('Islam','quran'),('Islam','prophet'),('Islam','mecca'),('Islam','medina'),('Islam','hajj'),('Islam','ramadan'),('Islam','fasting'),('Islam','zakat'),('Islam','charity'),('Islam','imam'),('Islam','minaret'),('Islam','mihrab'),('Islam','ablution'),('Islam','pilgrimage'),('Islam','kaaba'),('Islam','salah'),('Islam','sunnah'),('Islam','hadith'),('Islam','ummah'),('Islam','hijab'),('Islam','halal'),('Islam','haram'),('Islam','shahada'),
        ('education','school'),('education','teacher'),('education','student'),('education','classroom'),('education','textbook'),('education','homework'),('education','assignment'),('education','exam'),('education','grade'),('education','diploma'),('education','degree'),('education','university'),('education','college'),('education','library'),('education','research'),('education','lecture'),('education','seminar'),('education','laboratory'),('education','experiment'),('education','scholarship'),('education','curriculum'),('education','syllabus'),('education','semester'),('education','graduation'),('education','principal'),
        ('buildings','skyscraper'),('buildings','apartment'),('buildings','mansion'),('buildings','cottage'),('buildings','bungalow'),('buildings','villa'),('buildings','castle'),('buildings','palace'),('buildings','temple'),('buildings','cathedral'),('buildings','chapel'),('buildings','warehouse'),('buildings','factory'),('buildings','stadium'),('buildings','theater'),('buildings','museum'),('buildings','library'),('buildings','hospital'),('buildings','hotel'),('buildings','restaurant'),('buildings','shopping'),('buildings','office'),('buildings','tower'),('buildings','bridge'),('buildings','monument'),
        ('objects','telephone'),('objects','television'),('objects','computer'),('objects','camera'),('objects','clock'),('objects','watch'),('objects','mirror'),('objects','lamp'),('objects','chair'),('objects','table'),('objects','sofa'),('objects','bed'),('objects','pillow'),('objects','blanket'),('objects','curtain'),('objects','carpet'),('objects','painting'),('objects','vase'),('objects','bottle'),('objects','glass'),('objects','plate'),('objects','spoon'),('objects','fork'),('objects','knife'),('objects','scissors'),
        ('toys','doll'),('toys','teddy'),('toys','puzzle'),('toys','lego'),('toys','blocks'),('toys','train'),('toys','truck'),('toys','car'),('toys','airplane'),('toys','helicopter'),('toys','robot'),('toys','action'),('toys','skateboard'),('toys','bicycle'),('toys','scooter'),('toys','ball'),('toys','frisbee'),('toys','yoyo'),('toys','kite'),('toys','marbles'),('toys','cards'),('toys','board'),('toys','dice'),('toys','checkers'),('toys','chess'),
        ('countries','america'),('countries','canada'),('countries','mexico'),('countries','brazil'),('countries','argentina'),('countries','england'),('countries','france'),('countries','germany'),('countries','italy'),('countries','spain'),('countries','russia'),('countries','china'),('countries','japan'),('countries','india'),('countries','australia'),('countries','egypt'),('countries','nigeria'),('countries','kenya'),('countries','turkey'),('countries','pakistan'),('countries','indonesia'),('countries','thailand'),('countries','vietnam'),('countries','malaysia'),('countries','singapore')
    ]
    
    for topic, word in words:
        new_word = SecretWord(topic=topic, word=word)
        db.session.add(new_word)
    
    db.session.commit()
    print(f"Successfully added {len(words)} words to database!")